# This is a codemagic workflow file
# However, it is no longer in use. We have transitioned to utilizing the workflow editor instead.
workflows:
  sudoku-flutter-workflow:
    environment:
      java: 17
      flutter: 3.22.3
      android_signing:
        - ANDROID_KEYJKS
      groups:
        - githubtoken
    scripts:
      - name: build apk with flutter
        script: |
          
          export OPENCV_DART_ANDROID_ENABLED_ABI="arm64-v8a,armeabi-v7a"
          flutter build apk --release --target-platform=android-arm,android-arm64

    artifacts:
      - build/app/outputs/apk/**/*.apk
    publishing:
      scripts:
        - name: publish to Github
          script: | 
            #!/usr/bin/env zsh
            
            gh auth status \

            gh release create "${CM_TAG}" \
            -p \
            --title "Sudoku-Flutter#${CM_TAG} codemagic build" \
            build/app/outputs/apk/**/*.apk

